from django.db import models

class Siswa(models.Model):
    id = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=255)
    jenis_kelamin = models.CharField(max_length=10, blank=True, null=True)
    tanggal_lahir = models.DateField(blank=True, null=True)
    nomor_hp_orangtua = models.CharField(max_length=20, blank=True, null=True)
    email_orangtua = models.EmailField(max_length=255, blank=True, null=True)
    alamat = models.CharField(max_length=255, blank=True, null=True)
    agama = models.CharField(max_length=50, blank=True, null=True)
    ID_No = models.IntegerField(blank=True, null=True)
    NISN_No = models.CharField(max_length=20, blank=True, null=True)
    Student_Name = models.CharField(max_length=255, blank=True, null=True)
    Gender = models.CharField(max_length=10, blank=True, null=True)
    Place_of_Birth = models.CharField(max_length=100, blank=True, null=True)
    Date_of_Birth = models.DateField(blank=True, null=True)
    Home_Address = models.CharField(max_length=255, blank=True, null=True)
    StudentMobileNo = models.CharField(max_length=20, blank=True, null=True)
    Religion = models.CharField(max_length=50, blank=True, null=True)
    Child_No = models.IntegerField(blank=True, null=True)
    Family_Status = models.CharField(max_length=50, blank=True, null=True)
    Previous_School_Name = models.CharField(max_length=255, blank=True, null=True)
    Last_Grade = models.CharField(max_length=20, blank=True, null=True)
    AcceptedDate = models.DateField(blank=True, null=True)
    Nat_Grade = models.CharField(max_length=20, blank=True, null=True)
    School_Year = models.CharField(max_length=20, blank=True, null=True)
    Program = models.CharField(max_length=50, blank=True, null=True)
    FatherName = models.CharField(max_length=100, blank=True, null=True)
    FatherJob = models.CharField(max_length=100, blank=True, null=True)
    FatherAddress = models.CharField(max_length=255, blank=True, null=True)
    FatherMobileNo = models.CharField(max_length=20, blank=True, null=True)
    FatherEmail = models.EmailField(max_length=100, blank=True, null=True)
    MotherName = models.CharField(max_length=100, blank=True, null=True)
    MotherJob = models.CharField(max_length=100, blank=True, null=True)
    MotherAddress = models.CharField(max_length=255, blank=True, null=True)
    MotherMobileNo = models.CharField(max_length=20, blank=True, null=True)
    MotherEmail = models.EmailField(max_length=100, blank=True, null=True)
    GuardianName = models.CharField(max_length=100, blank=True, null=True)
    GuardianJob = models.CharField(max_length=100, blank=True, null=True)
    GuardianAddress = models.CharField(max_length=255, blank=True, null=True)
    GuardianMobileNo = models.CharField(max_length=20, blank=True, null=True)
    GuardianEmail = models.EmailField(max_length=100, blank=True, null=True)
    Book_ref1 = models.CharField(max_length=100, blank=True, null=True)
    Book_ref1_date = models.DateField(blank=True, null=True)
    Book_ref1_Principal = models.CharField(max_length=100, blank=True, null=True)
    Book_ref2 = models.CharField(max_length=100, blank=True, null=True)
    Book_ref2_date = models.DateField(blank=True, null=True)
    Book_ref2_Principal = models.CharField(max_length=100, blank=True, null=True)
    Book_ref3 = models.CharField(max_length=100, blank=True, null=True)
    Book_ref3_date = models.DateField(blank=True, null=True)
    Book_ref3_Principal = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        db_table = 'siswa'
        
    def __str__(self):
        return self.nama

